[general]
live_config_reload = true

[colors]
transparent_background_colors = true

[colors.bright]
black = "#666666"
blue = "#7aa6da"
cyan = "#70c0b1"
green = "#b9ca4a"
magenta = "#c397d8"
red = "#d54e53"
white = "#eaeaea"
yellow = "#e7c547"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "#131415"
blue = "#556a7d"
cyan = "#5b7d78"
green = "#777c44"
magenta = "#75617b"
red = "#864343"
white = "#828482"
yellow = "#9e824c"

[colors.hints.end]
background = "#1d1f21"
foreground = "#e9ff5e"

[colors.hints.start]
background = "#e9ff5e"
foreground = "#1d1f21"

[colors.normal]
black = "#1d1f21"
blue = "#81a2be"
cyan = "#8abeb7"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#c5c8c6"
yellow = "#f0c674"

[colors.primary]
background = "#000000"
foreground = "#c5c8c6"

[colors.search.focused_match]
background = "#000000"
foreground = "#ffffff"

[colors.search.matches]
background = "#ffffff"
foreground = "#000000"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
blink_interval = 100
blink_timeout = 5
thickness = 0.3
unfocused_hollow = true
vi_mode_style = "Block"

[env]
TERM = "alacritty"

# [font.normal]
# family = "CaskaydiaCove Nerd Font Mono"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 1

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[terminal.shell]
program = 'C:\Users\silvarc\scoop\apps\nu\current\nu.exe'

[window]
decorations = "full"
decorations_theme_variant = "None"
dynamic_padding = true
dynamic_title = false
opacity = 0.75
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 100
lines = 40

[window.padding]
x = 0
y = 0

[window.position]
x = 500
y = 200
